version: '3.8'

services:
  database:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: neuracraft
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  db-seed:
    build:
      context: .
      dockerfile: neuracraft/db-seed.Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:12345@database:3306/neuracraft
    command: >
      sh -c "while ! mysqladmin ping -h database -u root -p12345 --silent;
      do sleep 2; done && npx prisma migrate deploy && npm run db:seed"
    networks:
      - app-network

  web:
    build: ./neuracraft
    depends_on:
      - db-seed
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://root:12345@database:3306/neuracraft
      NEXTAUTH_URL: http://localhost:3000
      RECOMMENDER_URL: http://recommender:8000
      NEXTAUTH_SECRET: 12345
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: always

  recommender:
    build: ./recommender
    environment:
      RECOMMENDER_API_KEY: 12345
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge